# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Yim's Blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "Yim"

[params]
	name = "Yim's Blog"
	description = "Stop Talking,Start Doing"
	bio = "Programmer - Gopher"
	# Enter optionally your twitter account
	twitter = "LuYiyan"
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an enthusiastic gopher."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""
